language: python
python:
 - "3.5"
install:
 - rm -vf /etc/apt/sources.list.d/*riak* # Workaround on issue https://github.com/travis-ci/travis-ci/issues/8607
 - sudo apt-get update
 - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 # Useful for debugging any issues with conda
 - conda info -a
 - conda create -q -n test-environment python=3.5
 - source activate test-environment
 - conda install -c menpo mayavi
 - conda install networkx
 - conda install -c conda-forge nibabel
 - conda install pyqt=4
 - python setup.py install
 - conda install -c conda-forge codecov
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: 
 - python test/testBrainObj.py
 - coverage run test/testBrainObj.py
branches:
  only:
  - gh-pages
  - /.*/
after_success:
  - codecov
