# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mayBrain.ui'
#
# Created: Wed Jul  8 17:43:03 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Maybrain(object):
    def setupUi(self, Maybrain):
        Maybrain.setObjectName(_fromUtf8("Maybrain"))
        Maybrain.resize(831, 605)
        self.centralwidget = QtGui.QWidget(Maybrain)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.quitButton = QtGui.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(720, 530, 94, 24))
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 831, 521))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 821, 191))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.adjPlot = QtGui.QPushButton(self.groupBox)
        self.adjPlot.setEnabled(True)
        self.adjPlot.setGeometry(QtCore.QRect(650, 70, 71, 24))
        self.adjPlot.setObjectName(_fromUtf8("adjPlot"))
        self.spatialLabel = QtGui.QLabel(self.groupBox)
        self.spatialLabel.setGeometry(QtCore.QRect(20, 40, 121, 16))
        self.spatialLabel.setObjectName(_fromUtf8("spatialLabel"))
        self.skullLabel = QtGui.QLabel(self.groupBox)
        self.skullLabel.setGeometry(QtCore.QRect(20, 100, 121, 16))
        self.skullLabel.setObjectName(_fromUtf8("skullLabel"))
        self.skullFilename = QtGui.QLineEdit(self.groupBox)
        self.skullFilename.setGeometry(QtCore.QRect(150, 100, 391, 23))
        self.skullFilename.setObjectName(_fromUtf8("skullFilename"))
        self.skullLoad = QtGui.QPushButton(self.groupBox)
        self.skullLoad.setGeometry(QtCore.QRect(580, 100, 61, 24))
        self.skullLoad.setObjectName(_fromUtf8("skullLoad"))
        self.spatialFilename = QtGui.QLineEdit(self.groupBox)
        self.spatialFilename.setGeometry(QtCore.QRect(150, 40, 391, 23))
        self.spatialFilename.setObjectName(_fromUtf8("spatialFilename"))
        self.adjFilename = QtGui.QLineEdit(self.groupBox)
        self.adjFilename.setGeometry(QtCore.QRect(150, 70, 391, 23))
        self.adjFilename.setObjectName(_fromUtf8("adjFilename"))
        self.adjFnameButton = QtGui.QPushButton(self.groupBox)
        self.adjFnameButton.setGeometry(QtCore.QRect(550, 70, 21, 24))
        self.adjFnameButton.setObjectName(_fromUtf8("adjFnameButton"))
        self.brainLoad = QtGui.QPushButton(self.groupBox)
        self.brainLoad.setGeometry(QtCore.QRect(580, 70, 61, 24))
        self.brainLoad.setObjectName(_fromUtf8("brainLoad"))
        self.adjLabel = QtGui.QLabel(self.groupBox)
        self.adjLabel.setGeometry(QtCore.QRect(20, 70, 121, 16))
        self.adjLabel.setObjectName(_fromUtf8("adjLabel"))
        self.spatialFnameButton = QtGui.QPushButton(self.groupBox)
        self.spatialFnameButton.setGeometry(QtCore.QRect(550, 40, 21, 24))
        self.spatialFnameButton.setObjectName(_fromUtf8("spatialFnameButton"))
        self.skullFnameButton = QtGui.QPushButton(self.groupBox)
        self.skullFnameButton.setGeometry(QtCore.QRect(550, 100, 21, 24))
        self.skullFnameButton.setObjectName(_fromUtf8("skullFnameButton"))
        self.skullPlot = QtGui.QPushButton(self.groupBox)
        self.skullPlot.setEnabled(True)
        self.skullPlot.setGeometry(QtCore.QRect(650, 100, 71, 24))
        self.skullPlot.setObjectName(_fromUtf8("skullPlot"))
        self.thresholdValue = QtGui.QLineEdit(self.groupBox)
        self.thresholdValue.setGeometry(QtCore.QRect(730, 40, 71, 23))
        self.thresholdValue.setObjectName(_fromUtf8("thresholdValue"))
        self.thresholdLabel = QtGui.QLabel(self.groupBox)
        self.thresholdLabel.setGeometry(QtCore.QRect(580, 40, 71, 16))
        self.thresholdLabel.setObjectName(_fromUtf8("thresholdLabel"))
        self.tholdDropdown = QtGui.QComboBox(self.groupBox)
        self.tholdDropdown.setGeometry(QtCore.QRect(650, 40, 61, 22))
        self.tholdDropdown.setObjectName(_fromUtf8("tholdDropdown"))
        self.tholdDropdown.addItem(_fromUtf8(""))
        self.tholdDropdown.addItem(_fromUtf8(""))
        self.tholdDropdown.addItem(_fromUtf8(""))
        self.adjReplot = QtGui.QPushButton(self.groupBox)
        self.adjReplot.setEnabled(True)
        self.adjReplot.setGeometry(QtCore.QRect(730, 70, 71, 24))
        self.adjReplot.setObjectName(_fromUtf8("adjReplot"))
        self.brainName = QtGui.QLineEdit(self.groupBox)
        self.brainName.setGeometry(QtCore.QRect(560, 130, 231, 23))
        self.brainName.setObjectName(_fromUtf8("brainName"))
        self.brainNameLabel = QtGui.QLabel(self.groupBox)
        self.brainNameLabel.setGeometry(QtCore.QRect(480, 130, 81, 20))
        self.brainNameLabel.setObjectName(_fromUtf8("brainNameLabel"))
        self.plotNameLabel = QtGui.QLabel(self.groupBox)
        self.plotNameLabel.setGeometry(QtCore.QRect(480, 160, 81, 20))
        self.plotNameLabel.setObjectName(_fromUtf8("plotNameLabel"))
        self.plotName = QtGui.QLineEdit(self.groupBox)
        self.plotName.setGeometry(QtCore.QRect(560, 160, 231, 23))
        self.plotName.setObjectName(_fromUtf8("plotName"))
        self.hlBox = QtGui.QGroupBox(self.tab)
        self.hlBox.setGeometry(QtCore.QRect(10, 200, 821, 291))
        self.hlBox.setObjectName(_fromUtf8("hlBox"))
        self.hlPropLabel = QtGui.QLabel(self.hlBox)
        self.hlPropLabel.setGeometry(QtCore.QRect(20, 120, 81, 16))
        self.hlPropLabel.setObjectName(_fromUtf8("hlPropLabel"))
        self.hlValueLabel = QtGui.QLabel(self.hlBox)
        self.hlValueLabel.setGeometry(QtCore.QRect(260, 120, 61, 16))
        self.hlValueLabel.setObjectName(_fromUtf8("hlValueLabel"))
        self.subPlotName = QtGui.QLineEdit(self.hlBox)
        self.subPlotName.setGeometry(QtCore.QRect(380, 210, 171, 23))
        self.subPlotName.setObjectName(_fromUtf8("subPlotName"))
        self.subPlotNameLabel = QtGui.QLabel(self.hlBox)
        self.subPlotNameLabel.setGeometry(QtCore.QRect(380, 190, 101, 16))
        self.subPlotNameLabel.setObjectName(_fromUtf8("subPlotNameLabel"))
        self.propsFilename = QtGui.QLineEdit(self.hlBox)
        self.propsFilename.setGeometry(QtCore.QRect(150, 60, 381, 23))
        self.propsFilename.setObjectName(_fromUtf8("propsFilename"))
        self.propsLabel = QtGui.QLabel(self.hlBox)
        self.propsLabel.setGeometry(QtCore.QRect(20, 60, 121, 16))
        self.propsLabel.setObjectName(_fromUtf8("propsLabel"))
        self.propsFnameButton = QtGui.QPushButton(self.hlBox)
        self.propsFnameButton.setGeometry(QtCore.QRect(630, 60, 21, 24))
        self.propsFnameButton.setObjectName(_fromUtf8("propsFnameButton"))
        self.propsLoad = QtGui.QPushButton(self.hlBox)
        self.propsLoad.setGeometry(QtCore.QRect(660, 60, 61, 24))
        self.propsLoad.setObjectName(_fromUtf8("propsLoad"))
        self.hlApplyButton = QtGui.QPushButton(self.hlBox)
        self.hlApplyButton.setEnabled(True)
        self.hlApplyButton.setGeometry(QtCore.QRect(660, 130, 61, 24))
        self.hlApplyButton.setObjectName(_fromUtf8("hlApplyButton"))
        self.hlValue1 = QtGui.QLineEdit(self.hlBox)
        self.hlValue1.setGeometry(QtCore.QRect(260, 140, 41, 23))
        self.hlValue1.setObjectName(_fromUtf8("hlValue1"))
        self.hlRelationLabel = QtGui.QLabel(self.hlBox)
        self.hlRelationLabel.setGeometry(QtCore.QRect(150, 120, 61, 16))
        self.hlRelationLabel.setObjectName(_fromUtf8("hlRelationLabel"))
        self.hlValue2 = QtGui.QLineEdit(self.hlBox)
        self.hlValue2.setGeometry(QtCore.QRect(310, 140, 41, 23))
        self.hlValue2.setObjectName(_fromUtf8("hlValue2"))
        self.hlRelationBox = QtGui.QComboBox(self.hlBox)
        self.hlRelationBox.setGeometry(QtCore.QRect(150, 140, 78, 24))
        self.hlRelationBox.setObjectName(_fromUtf8("hlRelationBox"))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlNodesOrEdgesBox = QtGui.QComboBox(self.hlBox)
        self.hlNodesOrEdgesBox.setGeometry(QtCore.QRect(380, 140, 71, 24))
        self.hlNodesOrEdgesBox.setObjectName(_fromUtf8("hlNodesOrEdgesBox"))
        self.hlNodesOrEdgesBox.addItem(_fromUtf8(""))
        self.hlNodesOrEdgesBox.addItem(_fromUtf8(""))
        self.hlNodesOrEdgesBox.addItem(_fromUtf8(""))
        self.hlNodesOrEdgesLabel = QtGui.QLabel(self.hlBox)
        self.hlNodesOrEdgesLabel.setGeometry(QtCore.QRect(380, 120, 61, 16))
        self.hlNodesOrEdgesLabel.setObjectName(_fromUtf8("hlNodesOrEdgesLabel"))
        self.hlAddName = QtGui.QLabel(self.hlBox)
        self.hlAddName.setGeometry(QtCore.QRect(20, 100, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hlAddName.setFont(font)
        self.hlAddName.setObjectName(_fromUtf8("hlAddName"))
        self.hlValueLabel_2 = QtGui.QLabel(self.hlBox)
        self.hlValueLabel_2.setGeometry(QtCore.QRect(20, 170, 71, 16))
        self.hlValueLabel_2.setObjectName(_fromUtf8("hlValueLabel_2"))
        self.hlRedSpin = QtGui.QDoubleSpinBox(self.hlBox)
        self.hlRedSpin.setGeometry(QtCore.QRect(20, 210, 61, 23))
        self.hlRedSpin.setSingleStep(0.1)
        self.hlRedSpin.setObjectName(_fromUtf8("hlRedSpin"))
        self.hlGreenSpin = QtGui.QDoubleSpinBox(self.hlBox)
        self.hlGreenSpin.setGeometry(QtCore.QRect(90, 210, 61, 23))
        self.hlGreenSpin.setSingleStep(0.1)
        self.hlGreenSpin.setObjectName(_fromUtf8("hlGreenSpin"))
        self.hlBlueSpin = QtGui.QDoubleSpinBox(self.hlBox)
        self.hlBlueSpin.setGeometry(QtCore.QRect(160, 210, 61, 23))
        self.hlBlueSpin.setSingleStep(0.1)
        self.hlBlueSpin.setObjectName(_fromUtf8("hlBlueSpin"))
        self.hlValueLabel_3 = QtGui.QLabel(self.hlBox)
        self.hlValueLabel_3.setGeometry(QtCore.QRect(30, 190, 41, 16))
        self.hlValueLabel_3.setObjectName(_fromUtf8("hlValueLabel_3"))
        self.hlValueLabel_4 = QtGui.QLabel(self.hlBox)
        self.hlValueLabel_4.setGeometry(QtCore.QRect(100, 190, 41, 16))
        self.hlValueLabel_4.setObjectName(_fromUtf8("hlValueLabel_4"))
        self.hlValueLabel_6 = QtGui.QLabel(self.hlBox)
        self.hlValueLabel_6.setGeometry(QtCore.QRect(260, 170, 61, 16))
        self.hlValueLabel_6.setObjectName(_fromUtf8("hlValueLabel_6"))
        self.hlProp = QtGui.QComboBox(self.hlBox)
        self.hlProp.setGeometry(QtCore.QRect(20, 140, 121, 24))
        self.hlProp.setObjectName(_fromUtf8("hlProp"))
        self.hlProp.addItem(_fromUtf8(""))
        self.hlProp.addItem(_fromUtf8(""))
        self.hlProp.addItem(_fromUtf8(""))
        self.hlProp.addItem(_fromUtf8(""))
        self.hlValueLabel_5 = QtGui.QLabel(self.hlBox)
        self.hlValueLabel_5.setGeometry(QtCore.QRect(170, 190, 41, 16))
        self.hlValueLabel_5.setObjectName(_fromUtf8("hlValueLabel_5"))
        self.propAddName = QtGui.QLabel(self.hlBox)
        self.propAddName.setGeometry(QtCore.QRect(20, 30, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.propAddName.setFont(font)
        self.propAddName.setObjectName(_fromUtf8("propAddName"))
        self.hlOpacityValue = QtGui.QLineEdit(self.hlBox)
        self.hlOpacityValue.setGeometry(QtCore.QRect(260, 210, 61, 23))
        self.hlOpacityValue.setObjectName(_fromUtf8("hlOpacityValue"))
        self.hlBrainSelectName = QtGui.QLabel(self.hlBox)
        self.hlBrainSelectName.setGeometry(QtCore.QRect(480, 120, 61, 16))
        self.hlBrainSelectName.setObjectName(_fromUtf8("hlBrainSelectName"))
        self.hlBrainSelect = QtGui.QComboBox(self.hlBox)
        self.hlBrainSelect.setGeometry(QtCore.QRect(480, 140, 101, 24))
        self.hlBrainSelect.setObjectName(_fromUtf8("hlBrainSelect"))
        self.hlBrainSelect.addItem(_fromUtf8(""))
        self.propNodesOrEdgesBox_2 = QtGui.QComboBox(self.hlBox)
        self.propNodesOrEdgesBox_2.setGeometry(QtCore.QRect(540, 60, 71, 24))
        self.propNodesOrEdgesBox_2.setObjectName(_fromUtf8("propNodesOrEdgesBox_2"))
        self.propNodesOrEdgesBox_2.addItem(_fromUtf8(""))
        self.propNodesOrEdgesBox_2.addItem(_fromUtf8(""))
        self.propNodesOrEdgesLabel_2 = QtGui.QLabel(self.hlBox)
        self.propNodesOrEdgesLabel_2.setGeometry(QtCore.QRect(540, 40, 61, 16))
        self.propNodesOrEdgesLabel_2.setObjectName(_fromUtf8("propNodesOrEdgesLabel_2"))
        self.subPlotName_2 = QtGui.QLineEdit(self.hlBox)
        self.subPlotName_2.setGeometry(QtCore.QRect(480, 220, 171, 23))
        self.subPlotName_2.setObjectName(_fromUtf8("subPlotName_2"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.plotTree = QtGui.QTreeWidget(self.tab_2)
        self.plotTree.setGeometry(QtCore.QRect(340, 20, 461, 421))
        self.plotTree.setObjectName(_fromUtf8("plotTree"))
        self.opacitySlider = QtGui.QSlider(self.tab_2)
        self.opacitySlider.setGeometry(QtCore.QRect(50, 110, 160, 23))
        self.opacitySlider.setMaximum(99)
        self.opacitySlider.setPageStep(10)
        self.opacitySlider.setSliderPosition(99)
        self.opacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.opacitySlider.setObjectName(_fromUtf8("opacitySlider"))
        self.opacityLabel = QtGui.QLabel(self.tab_2)
        self.opacityLabel.setGeometry(QtCore.QRect(50, 80, 57, 15))
        self.opacityLabel.setObjectName(_fromUtf8("opacityLabel"))
        self.redSlider = QtGui.QSlider(self.tab_2)
        self.redSlider.setGeometry(QtCore.QRect(50, 180, 71, 23))
        self.redSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redSlider.setObjectName(_fromUtf8("redSlider"))
        self.greenSlider = QtGui.QSlider(self.tab_2)
        self.greenSlider.setGeometry(QtCore.QRect(140, 180, 71, 23))
        self.greenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.greenSlider.setObjectName(_fromUtf8("greenSlider"))
        self.blueSlider = QtGui.QSlider(self.tab_2)
        self.blueSlider.setGeometry(QtCore.QRect(220, 180, 71, 23))
        self.blueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueSlider.setObjectName(_fromUtf8("blueSlider"))
        self.colourLabel = QtGui.QLabel(self.tab_2)
        self.colourLabel.setGeometry(QtCore.QRect(50, 140, 57, 15))
        self.colourLabel.setObjectName(_fromUtf8("colourLabel"))
        self.redLabel = QtGui.QLabel(self.tab_2)
        self.redLabel.setGeometry(QtCore.QRect(50, 160, 57, 15))
        self.redLabel.setObjectName(_fromUtf8("redLabel"))
        self.greenLabel = QtGui.QLabel(self.tab_2)
        self.greenLabel.setGeometry(QtCore.QRect(150, 160, 57, 15))
        self.greenLabel.setObjectName(_fromUtf8("greenLabel"))
        self.blueLabel = QtGui.QLabel(self.tab_2)
        self.blueLabel.setGeometry(QtCore.QRect(230, 160, 57, 15))
        self.blueLabel.setObjectName(_fromUtf8("blueLabel"))
        self.redValueBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.redValueBox.setGeometry(QtCore.QRect(50, 210, 62, 23))
        self.redValueBox.setSingleStep(0.1)
        self.redValueBox.setObjectName(_fromUtf8("redValueBox"))
        self.greenValueBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.greenValueBox.setGeometry(QtCore.QRect(140, 210, 62, 23))
        self.greenValueBox.setSingleStep(0.1)
        self.greenValueBox.setObjectName(_fromUtf8("greenValueBox"))
        self.blueValueBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.blueValueBox.setGeometry(QtCore.QRect(220, 210, 62, 23))
        self.blueValueBox.setSingleStep(0.1)
        self.blueValueBox.setObjectName(_fromUtf8("blueValueBox"))
        self.visibleCheckBox = QtGui.QCheckBox(self.tab_2)
        self.visibleCheckBox.setGeometry(QtCore.QRect(50, 40, 111, 21))
        self.visibleCheckBox.setChecked(True)
        self.visibleCheckBox.setObjectName(_fromUtf8("visibleCheckBox"))
        self.opacityBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.opacityBox.setGeometry(QtCore.QRect(230, 110, 91, 23))
        self.opacityBox.setObjectName(_fromUtf8("opacityBox"))
        self.clearFigButton = QtGui.QPushButton(self.tab_2)
        self.clearFigButton.setGeometry(QtCore.QRect(30, 390, 94, 24))
        self.clearFigButton.setObjectName(_fromUtf8("clearFigButton"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.log = QtGui.QWidget()
        self.log.setObjectName(_fromUtf8("log"))
        self.textBrowser = QtGui.QTextBrowser(self.log)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 801, 411))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.pushButton = QtGui.QPushButton(self.log)
        self.pushButton.setGeometry(QtCore.QRect(20, 430, 94, 24))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget.addTab(self.log, _fromUtf8(""))
        Maybrain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Maybrain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        Maybrain.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Maybrain)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Maybrain.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(Maybrain)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSave_fig = QtGui.QAction(Maybrain)
        self.actionSave_fig.setObjectName(_fromUtf8("actionSave_fig"))
        self.menuFile.addAction(self.actionSave_fig)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(Maybrain)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Maybrain)

    def retranslateUi(self, Maybrain):
        Maybrain.setWindowTitle(_translate("Maybrain", "MainWindow", None))
        self.quitButton.setText(_translate("Maybrain", "Quit", None))
        self.groupBox.setTitle(_translate("Maybrain", "Basic info", None))
        self.adjPlot.setText(_translate("Maybrain", "Plot", None))
        self.spatialLabel.setText(_translate("Maybrain", "Node coordinate file", None))
        self.skullLabel.setText(_translate("Maybrain", "Skull file", None))
        self.skullLoad.setText(_translate("Maybrain", "Load", None))
        self.adjFnameButton.setText(_translate("Maybrain", "..", None))
        self.brainLoad.setText(_translate("Maybrain", "Load", None))
        self.adjLabel.setText(_translate("Maybrain", "Adjacency file", None))
        self.spatialFnameButton.setText(_translate("Maybrain", "..", None))
        self.skullFnameButton.setText(_translate("Maybrain", "..", None))
        self.skullPlot.setText(_translate("Maybrain", "Plot", None))
        self.thresholdValue.setText(_translate("Maybrain", "0", None))
        self.thresholdLabel.setText(_translate("Maybrain", "Threshold", None))
        self.tholdDropdown.setItemText(0, _translate("Maybrain", "Value", None))
        self.tholdDropdown.setItemText(1, _translate("Maybrain", "%", None))
        self.tholdDropdown.setItemText(2, _translate("Maybrain", "# edges", None))
        self.adjReplot.setText(_translate("Maybrain", "Replot", None))
        self.brainNameLabel.setText(_translate("Maybrain", "Brain Name", None))
        self.plotNameLabel.setText(_translate("Maybrain", "Plot Name", None))
        self.hlBox.setTitle(_translate("Maybrain", "Add properties and highlights", None))
        self.hlPropLabel.setText(_translate("Maybrain", "Property", None))
        self.hlValueLabel.setText(_translate("Maybrain", "Value", None))
        self.subPlotNameLabel.setText(_translate("Maybrain", "Name", None))
        self.propsLabel.setText(_translate("Maybrain", "Properties file", None))
        self.propsFnameButton.setText(_translate("Maybrain", "..", None))
        self.propsLoad.setText(_translate("Maybrain", "Load", None))
        self.hlApplyButton.setText(_translate("Maybrain", "Apply", None))
        self.hlValue1.setText(_translate("Maybrain", "0.00", None))
        self.hlRelationLabel.setText(_translate("Maybrain", "Relation", None))
        self.hlRelationBox.setItemText(0, _translate("Maybrain", "=", None))
        self.hlRelationBox.setItemText(1, _translate("Maybrain", ">", None))
        self.hlRelationBox.setItemText(2, _translate("Maybrain", "<", None))
        self.hlRelationBox.setItemText(3, _translate("Maybrain", ">=", None))
        self.hlRelationBox.setItemText(4, _translate("Maybrain", "<=", None))
        self.hlRelationBox.setItemText(5, _translate("Maybrain", "in()", None))
        self.hlRelationBox.setItemText(6, _translate("Maybrain", "in[)", None))
        self.hlRelationBox.setItemText(7, _translate("Maybrain", "in(]", None))
        self.hlRelationBox.setItemText(8, _translate("Maybrain", "in[]", None))
        self.hlRelationBox.setItemText(9, _translate("Maybrain", "contains text", None))
        self.hlNodesOrEdgesBox.setItemText(0, _translate("Maybrain", "nodes", None))
        self.hlNodesOrEdgesBox.setItemText(1, _translate("Maybrain", "edges", None))
        self.hlNodesOrEdgesBox.setItemText(2, _translate("Maybrain", "nodes and edges", None))
        self.hlNodesOrEdgesLabel.setText(_translate("Maybrain", "Apply to", None))
        self.hlAddName.setText(_translate("Maybrain", "Add a highlight", None))
        self.hlValueLabel_2.setText(_translate("Maybrain", "Colour", None))
        self.hlValueLabel_3.setText(_translate("Maybrain", "Red", None))
        self.hlValueLabel_4.setText(_translate("Maybrain", "Green", None))
        self.hlValueLabel_6.setText(_translate("Maybrain", "Opacity", None))
        self.hlProp.setItemText(0, _translate("Maybrain", "weight", None))
        self.hlProp.setItemText(1, _translate("Maybrain", "x", None))
        self.hlProp.setItemText(2, _translate("Maybrain", "y", None))
        self.hlProp.setItemText(3, _translate("Maybrain", "z", None))
        self.hlValueLabel_5.setText(_translate("Maybrain", "Blue", None))
        self.propAddName.setText(_translate("Maybrain", "Add a property", None))
        self.hlOpacityValue.setText(_translate("Maybrain", "0.00", None))
        self.hlBrainSelectName.setText(_translate("Maybrain", "Apply to", None))
        self.hlBrainSelect.setItemText(0, _translate("Maybrain", "select brain", None))
        self.propNodesOrEdgesBox_2.setItemText(0, _translate("Maybrain", "nodes", None))
        self.propNodesOrEdgesBox_2.setItemText(1, _translate("Maybrain", "edges", None))
        self.propNodesOrEdgesLabel_2.setText(_translate("Maybrain", "Apply to", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Maybrain", "General settings", None))
        self.plotTree.headerItem().setText(0, _translate("Maybrain", "Plot type", None))
        self.plotTree.headerItem().setText(1, _translate("Maybrain", "Plot name", None))
        self.opacityLabel.setText(_translate("Maybrain", "Opacity", None))
        self.colourLabel.setText(_translate("Maybrain", "Colour", None))
        self.redLabel.setText(_translate("Maybrain", "Red", None))
        self.greenLabel.setText(_translate("Maybrain", "Green", None))
        self.blueLabel.setText(_translate("Maybrain", "Blue", None))
        self.visibleCheckBox.setText(_translate("Maybrain", "Plot visible", None))
        self.clearFigButton.setText(_translate("Maybrain", "Clear figure", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Maybrain", "Adjust plot properties", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Maybrain", "Analysis", None))
        self.textBrowser.setHtml(_translate("Maybrain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\"># Python code to repeat what you\'ve just done with the buttons</span></p></body></html>", None))
        self.pushButton.setText(_translate("Maybrain", "save to file", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log), _translate("Maybrain", "Log", None))
        self.menuFile.setTitle(_translate("Maybrain", "File", None))
        self.menuAbout.setTitle(_translate("Maybrain", "About", None))
        self.actionAbout.setText(_translate("Maybrain", "About", None))
        self.actionSave_fig.setText(_translate("Maybrain", "Save fig", None))

