# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\martin\Downloads\mayBrain.ui'
#
# Created: Mon Jan 13 09:19:17 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(863, 605)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.quitButton = QtGui.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(740, 530, 94, 24))
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 831, 511))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 821, 131))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.adjPlot = QtGui.QPushButton(self.groupBox)
        self.adjPlot.setEnabled(True)
        self.adjPlot.setGeometry(QtCore.QRect(720, 70, 71, 24))
        self.adjPlot.setObjectName(_fromUtf8("adjPlot"))
        self.spatialLabel = QtGui.QLabel(self.groupBox)
        self.spatialLabel.setGeometry(QtCore.QRect(30, 40, 121, 16))
        self.spatialLabel.setObjectName(_fromUtf8("spatialLabel"))
        self.skullLabel = QtGui.QLabel(self.groupBox)
        self.skullLabel.setGeometry(QtCore.QRect(30, 100, 121, 16))
        self.skullLabel.setObjectName(_fromUtf8("skullLabel"))
        self.skullFilename = QtGui.QLineEdit(self.groupBox)
        self.skullFilename.setGeometry(QtCore.QRect(150, 100, 451, 23))
        self.skullFilename.setObjectName(_fromUtf8("skullFilename"))
        self.skullLoad = QtGui.QPushButton(self.groupBox)
        self.skullLoad.setGeometry(QtCore.QRect(650, 100, 61, 24))
        self.skullLoad.setObjectName(_fromUtf8("skullLoad"))
        self.spatialFilename = QtGui.QLineEdit(self.groupBox)
        self.spatialFilename.setGeometry(QtCore.QRect(150, 40, 451, 23))
        self.spatialFilename.setObjectName(_fromUtf8("spatialFilename"))
        self.adjFilename = QtGui.QLineEdit(self.groupBox)
        self.adjFilename.setGeometry(QtCore.QRect(150, 70, 451, 23))
        self.adjFilename.setObjectName(_fromUtf8("adjFilename"))
        self.adjFnameButton = QtGui.QPushButton(self.groupBox)
        self.adjFnameButton.setGeometry(QtCore.QRect(620, 70, 21, 24))
        self.adjFnameButton.setObjectName(_fromUtf8("adjFnameButton"))
        self.brainLoad = QtGui.QPushButton(self.groupBox)
        self.brainLoad.setGeometry(QtCore.QRect(650, 70, 61, 24))
        self.brainLoad.setObjectName(_fromUtf8("brainLoad"))
        self.adjLabel = QtGui.QLabel(self.groupBox)
        self.adjLabel.setGeometry(QtCore.QRect(30, 70, 121, 16))
        self.adjLabel.setObjectName(_fromUtf8("adjLabel"))
        self.spatialFnameButton = QtGui.QPushButton(self.groupBox)
        self.spatialFnameButton.setGeometry(QtCore.QRect(620, 40, 21, 24))
        self.spatialFnameButton.setObjectName(_fromUtf8("spatialFnameButton"))
        self.skullFnameButton = QtGui.QPushButton(self.groupBox)
        self.skullFnameButton.setGeometry(QtCore.QRect(620, 100, 21, 24))
        self.skullFnameButton.setObjectName(_fromUtf8("skullFnameButton"))
        self.skullPlot = QtGui.QPushButton(self.groupBox)
        self.skullPlot.setEnabled(True)
        self.skullPlot.setGeometry(QtCore.QRect(720, 100, 71, 24))
        self.skullPlot.setObjectName(_fromUtf8("skullPlot"))
        self.thresholdValue = QtGui.QLineEdit(self.groupBox)
        self.thresholdValue.setGeometry(QtCore.QRect(720, 40, 51, 23))
        self.thresholdValue.setObjectName(_fromUtf8("thresholdValue"))
        self.thresholdLabel = QtGui.QLabel(self.groupBox)
        self.thresholdLabel.setGeometry(QtCore.QRect(650, 40, 71, 16))
        self.thresholdLabel.setObjectName(_fromUtf8("thresholdLabel"))
        self.subPlotBox = QtGui.QGroupBox(self.tab)
        self.subPlotBox.setGeometry(QtCore.QRect(10, 140, 801, 211))
        self.subPlotBox.setObjectName(_fromUtf8("subPlotBox"))
        self.hlPropLabel = QtGui.QLabel(self.subPlotBox)
        self.hlPropLabel.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.hlPropLabel.setObjectName(_fromUtf8("hlPropLabel"))
        self.hlValueLabel = QtGui.QLabel(self.subPlotBox)
        self.hlValueLabel.setGeometry(QtCore.QRect(260, 90, 61, 16))
        self.hlValueLabel.setObjectName(_fromUtf8("hlValueLabel"))
        self.subPlotName = QtGui.QLineEdit(self.subPlotBox)
        self.subPlotName.setGeometry(QtCore.QRect(370, 110, 151, 23))
        self.subPlotName.setObjectName(_fromUtf8("subPlotName"))
        self.subPlotNameLabel = QtGui.QLabel(self.subPlotBox)
        self.subPlotNameLabel.setGeometry(QtCore.QRect(380, 90, 101, 16))
        self.subPlotNameLabel.setObjectName(_fromUtf8("subPlotNameLabel"))
        self.propsFilename = QtGui.QLineEdit(self.subPlotBox)
        self.propsFilename.setGeometry(QtCore.QRect(110, 30, 501, 23))
        self.propsFilename.setObjectName(_fromUtf8("propsFilename"))
        self.propsLabel = QtGui.QLabel(self.subPlotBox)
        self.propsLabel.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.propsLabel.setObjectName(_fromUtf8("propsLabel"))
        self.propsFnameButton = QtGui.QPushButton(self.subPlotBox)
        self.propsFnameButton.setGeometry(QtCore.QRect(620, 30, 21, 24))
        self.propsFnameButton.setObjectName(_fromUtf8("propsFnameButton"))
        self.propsLoad = QtGui.QPushButton(self.subPlotBox)
        self.propsLoad.setGeometry(QtCore.QRect(710, 30, 61, 24))
        self.propsLoad.setObjectName(_fromUtf8("propsLoad"))
        self.hlProp = QtGui.QLineEdit(self.subPlotBox)
        self.hlProp.setGeometry(QtCore.QRect(20, 110, 113, 23))
        self.hlProp.setObjectName(_fromUtf8("hlProp"))
        self.hlApplyButton = QtGui.QPushButton(self.subPlotBox)
        self.hlApplyButton.setEnabled(True)
        self.hlApplyButton.setGeometry(QtCore.QRect(710, 110, 61, 24))
        self.hlApplyButton.setObjectName(_fromUtf8("hlApplyButton"))
        self.hlValue1 = QtGui.QLineEdit(self.subPlotBox)
        self.hlValue1.setGeometry(QtCore.QRect(260, 110, 41, 23))
        self.hlValue1.setObjectName(_fromUtf8("hlValue1"))
        self.hlRelationLabel = QtGui.QLabel(self.subPlotBox)
        self.hlRelationLabel.setGeometry(QtCore.QRect(150, 90, 61, 16))
        self.hlRelationLabel.setObjectName(_fromUtf8("hlRelationLabel"))
        self.hlValue2 = QtGui.QLineEdit(self.subPlotBox)
        self.hlValue2.setGeometry(QtCore.QRect(310, 110, 41, 23))
        self.hlValue2.setObjectName(_fromUtf8("hlValue2"))
        self.hlRelationBox = QtGui.QComboBox(self.subPlotBox)
        self.hlRelationBox.setGeometry(QtCore.QRect(150, 110, 78, 24))
        self.hlRelationBox.setObjectName(_fromUtf8("hlRelationBox"))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlRelationBox.addItem(_fromUtf8(""))
        self.hlNodesOrEdgesBox = QtGui.QComboBox(self.subPlotBox)
        self.hlNodesOrEdgesBox.setGeometry(QtCore.QRect(530, 110, 78, 24))
        self.hlNodesOrEdgesBox.setObjectName(_fromUtf8("hlNodesOrEdgesBox"))
        self.hlNodesOrEdgesBox.addItem(_fromUtf8(""))
        self.hlNodesOrEdgesBox.addItem(_fromUtf8(""))
        self.hlNodesOrEdgesLabel = QtGui.QLabel(self.subPlotBox)
        self.hlNodesOrEdgesLabel.setGeometry(QtCore.QRect(530, 90, 61, 16))
        self.hlNodesOrEdgesLabel.setObjectName(_fromUtf8("hlNodesOrEdgesLabel"))
        self.hlAddName = QtGui.QLabel(self.subPlotBox)
        self.hlAddName.setGeometry(QtCore.QRect(20, 70, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hlAddName.setFont(font)
        self.hlAddName.setObjectName(_fromUtf8("hlAddName"))
        self.hlValueLabel_2 = QtGui.QLabel(self.subPlotBox)
        self.hlValueLabel_2.setGeometry(QtCore.QRect(390, 160, 41, 16))
        self.hlValueLabel_2.setObjectName(_fromUtf8("hlValueLabel_2"))
        self.hlRedSpin = QtGui.QDoubleSpinBox(self.subPlotBox)
        self.hlRedSpin.setGeometry(QtCore.QRect(450, 140, 51, 23))
        self.hlRedSpin.setObjectName(_fromUtf8("hlRedSpin"))
        self.hlGreenSpin = QtGui.QDoubleSpinBox(self.subPlotBox)
        self.hlGreenSpin.setGeometry(QtCore.QRect(450, 160, 51, 23))
        self.hlGreenSpin.setObjectName(_fromUtf8("hlGreenSpin"))
        self.hlBlueSpin = QtGui.QDoubleSpinBox(self.subPlotBox)
        self.hlBlueSpin.setGeometry(QtCore.QRect(450, 180, 51, 23))
        self.hlBlueSpin.setObjectName(_fromUtf8("hlBlueSpin"))
        self.hlValueLabel_3 = QtGui.QLabel(self.subPlotBox)
        self.hlValueLabel_3.setGeometry(QtCore.QRect(440, 140, 16, 16))
        self.hlValueLabel_3.setObjectName(_fromUtf8("hlValueLabel_3"))
        self.hlValueLabel_4 = QtGui.QLabel(self.subPlotBox)
        self.hlValueLabel_4.setGeometry(QtCore.QRect(440, 160, 16, 16))
        self.hlValueLabel_4.setObjectName(_fromUtf8("hlValueLabel_4"))
        self.hlValueLabel_5 = QtGui.QLabel(self.subPlotBox)
        self.hlValueLabel_5.setGeometry(QtCore.QRect(440, 180, 16, 16))
        self.hlValueLabel_5.setObjectName(_fromUtf8("hlValueLabel_5"))
        self.hlValueLabel_6 = QtGui.QLabel(self.subPlotBox)
        self.hlValueLabel_6.setGeometry(QtCore.QRect(530, 140, 61, 16))
        self.hlValueLabel_6.setObjectName(_fromUtf8("hlValueLabel_6"))
        self.hlOpacitySpin = QtGui.QDoubleSpinBox(self.subPlotBox)
        self.hlOpacitySpin.setGeometry(QtCore.QRect(530, 160, 62, 23))
        self.hlOpacitySpin.setObjectName(_fromUtf8("hlOpacitySpin"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 350, 521, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.figureSaveButton = QtGui.QPushButton(self.groupBox_3)
        self.figureSaveButton.setGeometry(QtCore.QRect(20, 60, 94, 24))
        self.figureSaveButton.setObjectName(_fromUtf8("figureSaveButton"))
        self.showFigCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.showFigCheckBox.setGeometry(QtCore.QRect(20, 30, 131, 21))
        self.showFigCheckBox.setChecked(True)
        self.showFigCheckBox.setObjectName(_fromUtf8("showFigCheckBox"))
        self.clearFigButton = QtGui.QPushButton(self.groupBox_3)
        self.clearFigButton.setGeometry(QtCore.QRect(210, 60, 94, 24))
        self.clearFigButton.setObjectName(_fromUtf8("clearFigButton"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.plotTree = QtGui.QTreeWidget(self.tab_2)
        self.plotTree.setGeometry(QtCore.QRect(340, 20, 461, 421))
        self.plotTree.setObjectName(_fromUtf8("plotTree"))
        self.opacitySlider = QtGui.QSlider(self.tab_2)
        self.opacitySlider.setGeometry(QtCore.QRect(50, 110, 160, 23))
        self.opacitySlider.setMaximum(99)
        self.opacitySlider.setPageStep(10)
        self.opacitySlider.setSliderPosition(99)
        self.opacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.opacitySlider.setObjectName(_fromUtf8("opacitySlider"))
        self.opacityLabel = QtGui.QLabel(self.tab_2)
        self.opacityLabel.setGeometry(QtCore.QRect(50, 80, 57, 15))
        self.opacityLabel.setObjectName(_fromUtf8("opacityLabel"))
        self.redSlider = QtGui.QSlider(self.tab_2)
        self.redSlider.setGeometry(QtCore.QRect(50, 180, 71, 23))
        self.redSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redSlider.setObjectName(_fromUtf8("redSlider"))
        self.greenSlider = QtGui.QSlider(self.tab_2)
        self.greenSlider.setGeometry(QtCore.QRect(140, 180, 71, 23))
        self.greenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.greenSlider.setObjectName(_fromUtf8("greenSlider"))
        self.blueSlider = QtGui.QSlider(self.tab_2)
        self.blueSlider.setGeometry(QtCore.QRect(220, 180, 71, 23))
        self.blueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueSlider.setObjectName(_fromUtf8("blueSlider"))
        self.colourLabel = QtGui.QLabel(self.tab_2)
        self.colourLabel.setGeometry(QtCore.QRect(50, 140, 57, 15))
        self.colourLabel.setObjectName(_fromUtf8("colourLabel"))
        self.redLabel = QtGui.QLabel(self.tab_2)
        self.redLabel.setGeometry(QtCore.QRect(50, 160, 57, 15))
        self.redLabel.setObjectName(_fromUtf8("redLabel"))
        self.greenLabel = QtGui.QLabel(self.tab_2)
        self.greenLabel.setGeometry(QtCore.QRect(150, 160, 57, 15))
        self.greenLabel.setObjectName(_fromUtf8("greenLabel"))
        self.blueLabel = QtGui.QLabel(self.tab_2)
        self.blueLabel.setGeometry(QtCore.QRect(230, 160, 57, 15))
        self.blueLabel.setObjectName(_fromUtf8("blueLabel"))
        self.redValueBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.redValueBox.setGeometry(QtCore.QRect(50, 210, 62, 23))
        self.redValueBox.setObjectName(_fromUtf8("redValueBox"))
        self.greenValueBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.greenValueBox.setGeometry(QtCore.QRect(140, 210, 62, 23))
        self.greenValueBox.setObjectName(_fromUtf8("greenValueBox"))
        self.blueValueBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.blueValueBox.setGeometry(QtCore.QRect(220, 210, 62, 23))
        self.blueValueBox.setObjectName(_fromUtf8("blueValueBox"))
        self.visibleCheckBox = QtGui.QCheckBox(self.tab_2)
        self.visibleCheckBox.setGeometry(QtCore.QRect(50, 40, 111, 21))
        self.visibleCheckBox.setChecked(True)
        self.visibleCheckBox.setObjectName(_fromUtf8("visibleCheckBox"))
        self.opacityBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.opacityBox.setGeometry(QtCore.QRect(230, 110, 91, 23))
        self.opacityBox.setObjectName(_fromUtf8("opacityBox"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.log = QtGui.QWidget()
        self.log.setObjectName(_fromUtf8("log"))
        self.textBrowser = QtGui.QTextBrowser(self.log)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 801, 411))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.pushButton = QtGui.QPushButton(self.log)
        self.pushButton.setGeometry(QtCore.QRect(20, 430, 94, 24))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget.addTab(self.log, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSave_fig = QtGui.QAction(MainWindow)
        self.actionSave_fig.setObjectName(_fromUtf8("actionSave_fig"))
        self.menuFile.addAction(self.actionSave_fig)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.quitButton.setText(_translate("MainWindow", "Quit", None))
        self.groupBox.setTitle(_translate("MainWindow", "Basic info", None))
        self.adjPlot.setText(_translate("MainWindow", "Plot", None))
        self.spatialLabel.setText(_translate("MainWindow", "Node coordinate file", None))
        self.skullLabel.setText(_translate("MainWindow", "Skull file", None))
        self.skullLoad.setText(_translate("MainWindow", "Load", None))
        self.adjFnameButton.setText(_translate("MainWindow", "..", None))
        self.brainLoad.setText(_translate("MainWindow", "Load", None))
        self.adjLabel.setText(_translate("MainWindow", "Adjacency file", None))
        self.spatialFnameButton.setText(_translate("MainWindow", "..", None))
        self.skullFnameButton.setText(_translate("MainWindow", "..", None))
        self.skullPlot.setText(_translate("MainWindow", "Plot", None))
        self.thresholdValue.setText(_translate("MainWindow", "0", None))
        self.thresholdLabel.setText(_translate("MainWindow", "Threshold", None))
        self.subPlotBox.setTitle(_translate("MainWindow", "Add properties and highlights", None))
        self.hlPropLabel.setText(_translate("MainWindow", "Property", None))
        self.hlValueLabel.setText(_translate("MainWindow", "Value", None))
        self.subPlotNameLabel.setText(_translate("MainWindow", "Name", None))
        self.propsLabel.setText(_translate("MainWindow", "Properties file", None))
        self.propsFnameButton.setText(_translate("MainWindow", "..", None))
        self.propsLoad.setText(_translate("MainWindow", "Load", None))
        self.hlApplyButton.setText(_translate("MainWindow", "Apply", None))
        self.hlRelationLabel.setText(_translate("MainWindow", "Relation", None))
        self.hlRelationBox.setItemText(0, _translate("MainWindow", "=", None))
        self.hlRelationBox.setItemText(1, _translate("MainWindow", ">", None))
        self.hlRelationBox.setItemText(2, _translate("MainWindow", "<", None))
        self.hlRelationBox.setItemText(3, _translate("MainWindow", ">=", None))
        self.hlRelationBox.setItemText(4, _translate("MainWindow", "<=", None))
        self.hlRelationBox.setItemText(5, _translate("MainWindow", "in()", None))
        self.hlRelationBox.setItemText(6, _translate("MainWindow", "in[)", None))
        self.hlRelationBox.setItemText(7, _translate("MainWindow", "in(]", None))
        self.hlRelationBox.setItemText(8, _translate("MainWindow", "in[]", None))
        self.hlRelationBox.setItemText(9, _translate("MainWindow", "contains text", None))
        self.hlNodesOrEdgesBox.setItemText(0, _translate("MainWindow", "nodes", None))
        self.hlNodesOrEdgesBox.setItemText(1, _translate("MainWindow", "edges", None))
        self.hlNodesOrEdgesLabel.setText(_translate("MainWindow", "Apply to", None))
        self.hlAddName.setText(_translate("MainWindow", "Add a highlight", None))
        self.hlValueLabel_2.setText(_translate("MainWindow", "Colour", None))
        self.hlValueLabel_3.setText(_translate("MainWindow", "R", None))
        self.hlValueLabel_4.setText(_translate("MainWindow", "G", None))
        self.hlValueLabel_5.setText(_translate("MainWindow", "B", None))
        self.hlValueLabel_6.setText(_translate("MainWindow", "Opacity", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Figure options", None))
        self.figureSaveButton.setText(_translate("MainWindow", "Save as...", None))
        self.showFigCheckBox.setText(_translate("MainWindow", "show figure", None))
        self.clearFigButton.setText(_translate("MainWindow", "Clear figure", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "General settings", None))
        self.plotTree.headerItem().setText(0, _translate("MainWindow", "Plot type", None))
        self.plotTree.headerItem().setText(1, _translate("MainWindow", "Plot name", None))
        self.opacityLabel.setText(_translate("MainWindow", "Opacity", None))
        self.colourLabel.setText(_translate("MainWindow", "Colour", None))
        self.redLabel.setText(_translate("MainWindow", "Red", None))
        self.greenLabel.setText(_translate("MainWindow", "Green", None))
        self.blueLabel.setText(_translate("MainWindow", "Blue", None))
        self.visibleCheckBox.setText(_translate("MainWindow", "Plot visible", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Adjust plot properties", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Analysis", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"># Python code to repeat what you\'ve just done with the buttons</p></body></html>", None))
        self.pushButton.setText(_translate("MainWindow", "save to file", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log), _translate("MainWindow", "Log", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionSave_fig.setText(_translate("MainWindow", "Save fig", None))

