# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mayBrain.ui'
#
# Created: Wed Oct 31 20:53:55 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(863, 605)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.quitButton = QtGui.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(740, 530, 94, 24))
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 831, 511))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 821, 181))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.propsFilename = QtGui.QLineEdit(self.groupBox)
        self.propsFilename.setGeometry(QtCore.QRect(130, 130, 471, 23))
        self.propsFilename.setObjectName(_fromUtf8("propsFilename"))
        self.adjPlot = QtGui.QPushButton(self.groupBox)
        self.adjPlot.setEnabled(False)
        self.adjPlot.setGeometry(QtCore.QRect(720, 70, 71, 24))
        self.adjPlot.setObjectName(_fromUtf8("adjPlot"))
        self.spatialLabel = QtGui.QLabel(self.groupBox)
        self.spatialLabel.setGeometry(QtCore.QRect(30, 40, 121, 16))
        self.spatialLabel.setObjectName(_fromUtf8("spatialLabel"))
        self.spatialPlot = QtGui.QPushButton(self.groupBox)
        self.spatialPlot.setEnabled(False)
        self.spatialPlot.setGeometry(QtCore.QRect(720, 40, 71, 24))
        self.spatialPlot.setObjectName(_fromUtf8("spatialPlot"))
        self.spatialLoad = QtGui.QPushButton(self.groupBox)
        self.spatialLoad.setGeometry(QtCore.QRect(650, 40, 61, 24))
        self.spatialLoad.setObjectName(_fromUtf8("spatialLoad"))
        self.propsFnameButton = QtGui.QPushButton(self.groupBox)
        self.propsFnameButton.setGeometry(QtCore.QRect(620, 130, 21, 24))
        self.propsFnameButton.setObjectName(_fromUtf8("propsFnameButton"))
        self.propsLabel = QtGui.QLabel(self.groupBox)
        self.propsLabel.setGeometry(QtCore.QRect(30, 130, 121, 16))
        self.propsLabel.setObjectName(_fromUtf8("propsLabel"))
        self.skullLabel = QtGui.QLabel(self.groupBox)
        self.skullLabel.setGeometry(QtCore.QRect(30, 100, 121, 16))
        self.skullLabel.setObjectName(_fromUtf8("skullLabel"))
        self.skullFilename = QtGui.QLineEdit(self.groupBox)
        self.skullFilename.setGeometry(QtCore.QRect(130, 100, 471, 23))
        self.skullFilename.setObjectName(_fromUtf8("skullFilename"))
        self.skullLoad = QtGui.QPushButton(self.groupBox)
        self.skullLoad.setGeometry(QtCore.QRect(650, 100, 61, 24))
        self.skullLoad.setObjectName(_fromUtf8("skullLoad"))
        self.spatialFilename = QtGui.QLineEdit(self.groupBox)
        self.spatialFilename.setGeometry(QtCore.QRect(130, 40, 471, 23))
        self.spatialFilename.setObjectName(_fromUtf8("spatialFilename"))
        self.adjFilename = QtGui.QLineEdit(self.groupBox)
        self.adjFilename.setGeometry(QtCore.QRect(130, 70, 471, 23))
        self.adjFilename.setObjectName(_fromUtf8("adjFilename"))
        self.adjFnameButton = QtGui.QPushButton(self.groupBox)
        self.adjFnameButton.setGeometry(QtCore.QRect(620, 70, 21, 24))
        self.adjFnameButton.setObjectName(_fromUtf8("adjFnameButton"))
        self.adjLoad = QtGui.QPushButton(self.groupBox)
        self.adjLoad.setGeometry(QtCore.QRect(650, 70, 61, 24))
        self.adjLoad.setObjectName(_fromUtf8("adjLoad"))
        self.propsLoad = QtGui.QPushButton(self.groupBox)
        self.propsLoad.setGeometry(QtCore.QRect(650, 130, 61, 24))
        self.propsLoad.setObjectName(_fromUtf8("propsLoad"))
        self.adjLabel = QtGui.QLabel(self.groupBox)
        self.adjLabel.setGeometry(QtCore.QRect(30, 70, 121, 16))
        self.adjLabel.setObjectName(_fromUtf8("adjLabel"))
        self.spatialFnameButton = QtGui.QPushButton(self.groupBox)
        self.spatialFnameButton.setGeometry(QtCore.QRect(620, 40, 21, 24))
        self.spatialFnameButton.setObjectName(_fromUtf8("spatialFnameButton"))
        self.skullFnameButton = QtGui.QPushButton(self.groupBox)
        self.skullFnameButton.setGeometry(QtCore.QRect(620, 100, 21, 24))
        self.skullFnameButton.setObjectName(_fromUtf8("skullFnameButton"))
        self.skullPlot = QtGui.QPushButton(self.groupBox)
        self.skullPlot.setEnabled(False)
        self.skullPlot.setGeometry(QtCore.QRect(720, 100, 71, 24))
        self.skullPlot.setObjectName(_fromUtf8("skullPlot"))
        self.subPlotBox = QtGui.QGroupBox(self.tab)
        self.subPlotBox.setGeometry(QtCore.QRect(10, 200, 791, 111))
        self.subPlotBox.setObjectName(_fromUtf8("subPlotBox"))
        self.subPlotButton = QtGui.QPushButton(self.subPlotBox)
        self.subPlotButton.setEnabled(True)
        self.subPlotButton.setGeometry(QtCore.QRect(500, 60, 71, 24))
        self.subPlotButton.setObjectName(_fromUtf8("subPlotButton"))
        self.subPlotValue = QtGui.QLineEdit(self.subPlotBox)
        self.subPlotValue.setGeometry(QtCore.QRect(180, 60, 113, 23))
        self.subPlotValue.setObjectName(_fromUtf8("subPlotValue"))
        self.subPlotPropLabel = QtGui.QLabel(self.subPlotBox)
        self.subPlotPropLabel.setGeometry(QtCore.QRect(30, 40, 81, 16))
        self.subPlotPropLabel.setObjectName(_fromUtf8("subPlotPropLabel"))
        self.subPlotProp = QtGui.QComboBox(self.subPlotBox)
        self.subPlotProp.setGeometry(QtCore.QRect(30, 60, 111, 24))
        self.subPlotProp.setObjectName(_fromUtf8("subPlotProp"))
        self.subPlotProp.addItem(_fromUtf8(""))
        self.subPlotProp.addItem(_fromUtf8(""))
        self.subPlotValueLabel = QtGui.QLabel(self.subPlotBox)
        self.subPlotValueLabel.setGeometry(QtCore.QRect(180, 40, 61, 16))
        self.subPlotValueLabel.setObjectName(_fromUtf8("subPlotValueLabel"))
        self.subPlotName = QtGui.QLineEdit(self.subPlotBox)
        self.subPlotName.setGeometry(QtCore.QRect(310, 60, 181, 23))
        self.subPlotName.setObjectName(_fromUtf8("subPlotName"))
        self.subPlotNameLabel = QtGui.QLabel(self.subPlotBox)
        self.subPlotNameLabel.setGeometry(QtCore.QRect(320, 40, 181, 16))
        self.subPlotNameLabel.setObjectName(_fromUtf8("subPlotNameLabel"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 320, 521, 111))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.figureSaveButton = QtGui.QPushButton(self.groupBox_3)
        self.figureSaveButton.setGeometry(QtCore.QRect(20, 60, 94, 24))
        self.figureSaveButton.setObjectName(_fromUtf8("figureSaveButton"))
        self.showFigCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.showFigCheckBox.setGeometry(QtCore.QRect(20, 30, 131, 21))
        self.showFigCheckBox.setChecked(True)
        self.showFigCheckBox.setObjectName(_fromUtf8("showFigCheckBox"))
        self.clearFigButton = QtGui.QPushButton(self.groupBox_3)
        self.clearFigButton.setGeometry(QtCore.QRect(210, 60, 94, 24))
        self.clearFigButton.setObjectName(_fromUtf8("clearFigButton"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.plotTree = QtGui.QTreeWidget(self.tab_2)
        self.plotTree.setGeometry(QtCore.QRect(490, 20, 311, 421))
        self.plotTree.setObjectName(_fromUtf8("plotTree"))
        self.opacitySlider = QtGui.QSlider(self.tab_2)
        self.opacitySlider.setGeometry(QtCore.QRect(50, 110, 160, 23))
        self.opacitySlider.setMaximum(99)
        self.opacitySlider.setPageStep(10)
        self.opacitySlider.setSliderPosition(99)
        self.opacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.opacitySlider.setObjectName(_fromUtf8("opacitySlider"))
        self.opacityLabel = QtGui.QLabel(self.tab_2)
        self.opacityLabel.setGeometry(QtCore.QRect(50, 80, 57, 15))
        self.opacityLabel.setObjectName(_fromUtf8("opacityLabel"))
        self.redSlider = QtGui.QSlider(self.tab_2)
        self.redSlider.setGeometry(QtCore.QRect(50, 180, 71, 23))
        self.redSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redSlider.setObjectName(_fromUtf8("redSlider"))
        self.greenSlider = QtGui.QSlider(self.tab_2)
        self.greenSlider.setGeometry(QtCore.QRect(140, 180, 71, 23))
        self.greenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.greenSlider.setObjectName(_fromUtf8("greenSlider"))
        self.blueSlider = QtGui.QSlider(self.tab_2)
        self.blueSlider.setGeometry(QtCore.QRect(220, 180, 71, 23))
        self.blueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueSlider.setObjectName(_fromUtf8("blueSlider"))
        self.colourLabel = QtGui.QLabel(self.tab_2)
        self.colourLabel.setGeometry(QtCore.QRect(50, 140, 57, 15))
        self.colourLabel.setObjectName(_fromUtf8("colourLabel"))
        self.redLabel = QtGui.QLabel(self.tab_2)
        self.redLabel.setGeometry(QtCore.QRect(50, 160, 57, 15))
        self.redLabel.setObjectName(_fromUtf8("redLabel"))
        self.greenLabel = QtGui.QLabel(self.tab_2)
        self.greenLabel.setGeometry(QtCore.QRect(150, 160, 57, 15))
        self.greenLabel.setObjectName(_fromUtf8("greenLabel"))
        self.blueLabel = QtGui.QLabel(self.tab_2)
        self.blueLabel.setGeometry(QtCore.QRect(230, 160, 57, 15))
        self.blueLabel.setObjectName(_fromUtf8("blueLabel"))
        self.redValueBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.redValueBox.setGeometry(QtCore.QRect(50, 210, 62, 23))
        self.redValueBox.setObjectName(_fromUtf8("redValueBox"))
        self.greenValueBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.greenValueBox.setGeometry(QtCore.QRect(140, 210, 62, 23))
        self.greenValueBox.setObjectName(_fromUtf8("greenValueBox"))
        self.blueValueBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.blueValueBox.setGeometry(QtCore.QRect(220, 210, 62, 23))
        self.blueValueBox.setObjectName(_fromUtf8("blueValueBox"))
        self.visibleCheckBox = QtGui.QCheckBox(self.tab_2)
        self.visibleCheckBox.setGeometry(QtCore.QRect(50, 40, 111, 21))
        self.visibleCheckBox.setChecked(True)
        self.visibleCheckBox.setObjectName(_fromUtf8("visibleCheckBox"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.log = QtGui.QWidget()
        self.log.setObjectName(_fromUtf8("log"))
        self.textBrowser = QtGui.QTextBrowser(self.log)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 801, 411))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.pushButton = QtGui.QPushButton(self.log)
        self.pushButton.setGeometry(QtCore.QRect(20, 430, 94, 24))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget.addTab(self.log, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSave_fig = QtGui.QAction(MainWindow)
        self.actionSave_fig.setObjectName(_fromUtf8("actionSave_fig"))
        self.menuFile.addAction(self.actionSave_fig)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Basic info", None, QtGui.QApplication.UnicodeUTF8))
        self.adjPlot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.spatialLabel.setText(QtGui.QApplication.translate("MainWindow", "Spatial info file", None, QtGui.QApplication.UnicodeUTF8))
        self.spatialPlot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.spatialLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.propsFnameButton.setText(QtGui.QApplication.translate("MainWindow", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.propsLabel.setText(QtGui.QApplication.translate("MainWindow", "Properties file", None, QtGui.QApplication.UnicodeUTF8))
        self.skullLabel.setText(QtGui.QApplication.translate("MainWindow", "Skull file", None, QtGui.QApplication.UnicodeUTF8))
        self.skullLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.adjFnameButton.setText(QtGui.QApplication.translate("MainWindow", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.adjLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.propsLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.adjLabel.setText(QtGui.QApplication.translate("MainWindow", "Adjacency file", None, QtGui.QApplication.UnicodeUTF8))
        self.spatialFnameButton.setText(QtGui.QApplication.translate("MainWindow", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.skullFnameButton.setText(QtGui.QApplication.translate("MainWindow", "..", None, QtGui.QApplication.UnicodeUTF8))
        self.skullPlot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.subPlotBox.setTitle(QtGui.QApplication.translate("MainWindow", "Add sub-plots", None, QtGui.QApplication.UnicodeUTF8))
        self.subPlotButton.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.subPlotPropLabel.setText(QtGui.QApplication.translate("MainWindow", "Property", None, QtGui.QApplication.UnicodeUTF8))
        self.subPlotProp.setItemText(0, QtGui.QApplication.translate("MainWindow", "Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.subPlotProp.setItemText(1, QtGui.QApplication.translate("MainWindow", "Weight", None, QtGui.QApplication.UnicodeUTF8))
        self.subPlotValueLabel.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.subPlotNameLabel.setText(QtGui.QApplication.translate("MainWindow", "Plot name (can be left blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Figure options", None, QtGui.QApplication.UnicodeUTF8))
        self.figureSaveButton.setText(QtGui.QApplication.translate("MainWindow", "Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.showFigCheckBox.setText(QtGui.QApplication.translate("MainWindow", "show figure", None, QtGui.QApplication.UnicodeUTF8))
        self.clearFigButton.setText(QtGui.QApplication.translate("MainWindow", "Clear figure", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "General settings", None, QtGui.QApplication.UnicodeUTF8))
        self.plotTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Plot name", None, QtGui.QApplication.UnicodeUTF8))
        self.opacityLabel.setText(QtGui.QApplication.translate("MainWindow", "Opacity", None, QtGui.QApplication.UnicodeUTF8))
        self.colourLabel.setText(QtGui.QApplication.translate("MainWindow", "Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.redLabel.setText(QtGui.QApplication.translate("MainWindow", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.greenLabel.setText(QtGui.QApplication.translate("MainWindow", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.blueLabel.setText(QtGui.QApplication.translate("MainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.visibleCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Plot visible", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Adjust plot properties", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"># Python code to repeat what you\'ve just done with the buttons</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "save to file", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log), QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_fig.setText(QtGui.QApplication.translate("MainWindow", "Save fig", None, QtGui.QApplication.UnicodeUTF8))

