import matplotlib.pyplot as plt
import numpy as np
import networkx as nx
from nilearn import plotting
from maybrain import constants as ct


def show():
    """
    Show all the figures generated by matplotlib
    This function is equivalent to :func:`matplotlib.pyplot.show`.
    """
    plt.show()


def plot_connectome(brain, **kwargs):
    """ 
    Wrapper over `nilearn.plotting.plot_connectome` to plot connectome of a brain.

    Brain's nodes should have `constants.XYZ` attribute (spatial information)

    Parameters
    ----------
    brain: maybrain.brain.Brain
        An instance of the `Brain` class
    kwargs
        Keyword arguments if you need to pass them to nilearn's plot_connectome()

    Returns
    -------
    display
        the display from nilearn (return from plot_connectome)
    """
    if 'edge_cmap' not in kwargs:
        kwargs['edge_cmap'] = plt.get_cmap('YlGnBu')
    if 'node_color' not in kwargs:
        kwargs['node_color'] = 'red'

    return plotting.plot_connectome(np.copy(nx.to_numpy_matrix(brain.G, nonedge=0)),
                                    list(dict(brain.G.nodes(data=ct.XYZ)).values()),
                                    **kwargs)
